{
 "title": "MultiCloud",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Log Messages",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "vendor_log_total" }
   ]
  },
  {
   "title": "JDBC Connections",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "vendor_agroal_active_count" },
    { "expr": "vendor_agroal_available_count" }
   ]
  },
  {
   "title": "Batch Retrievals",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "application_com_cloudyengineering_ticketing_AssigneeResource_performedRetrievals_total"
    },
    {
     "expr": "application_com_cloudyengineering_ticketing_AssigneeResource_checksTimer_rate_per_second"
    }
   ]
  },
  {
   "title": "Application Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "vendor_memoryPool_usage_max_bytes"
    }
   ]
  }
 ]
}