# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ main, 'FEATURE/**' ]
  pull_request:
    branches: [ '**' ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11.0.2
      uses: actions/setup-java@v1
      with:
        java-version: 11.0.2
    - name: Build with Maven
      env:
        DOCKERHUB_SECRET: ${{secrets.DOCKER_HUB_SECRET}}
        DOCKERHUB_USERNAME: ${{secrets.DOCKER_HUB_USERNAME}}
      run: ./mvnw -B package --file pom.xml -Dquarkus.container-image.push=true -Dquarkus.container-image.username=$DOCKERHUB_USERNAME -Dquarkus.container-image.password=$DOCKERHUB_SECRET
